services:
  strapi:
    image: node:18-alpine # Using Node.js 18.x for compatibility
    container_name: strapi
    working_dir: /srv/app
    volumes:
      - ./:/srv/app  # Mount the project directory inside the container
      - /srv/app/node_modules  # Local node_modules directory (only inside the container)
    ports:
      - "1337:1337"
    env_file:
      - .env  # Reference to the .env file
    command: sh -c "yarn install && yarn build && yarn start"  # Ensure install and develop are run sequentially
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: postgres
    env_file:
      - .env  # Reference to the .env file
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
