services:
  strapi:
    image: node:18-alpine # Using Node.js 18.x for compatibility
    container_name: strapi
    working_dir: /srv/app
    volumes:
      - ./:/srv/app  # Correct path to content-admin directory
      - /srv/app/node_modules  
    ports:
      - "1337:1337"
    env_file:
      - .env  # Reference to the .env file
    command: "yarn start"
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: postgres
    env_file:
      - .env  # Reference to the .env file
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
