name: Deploy to DigitalOcean

on:
  workflow_dispatch:  # Manual trigger for deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DO_HOST: ${{ vars.DO_HOST }}
      DO_USERNAME: ${{ vars.DO_USERNAME }}
      DO_PASSWORD: ${{ vars.DO_PASSWORD }}
      DATABASE_CLIENT: ${{ vars.DATABASE_CLIENT }}
      DATABASE_HOST: ${{ vars.DATABASE_HOST }}
      DATABASE_PORT: ${{ vars.DATABASE_PORT }}
      DATABASE_NAME: ${{ vars.DATABASE_NAME }}
      DATABASE_USERNAME: ${{ vars.DATABASE_USERNAME }}
      DATABASE_PASSWORD: ${{ vars.DATABASE_PASSWORD }}
      APP_KEYS: ${{ vars.APP_KEYS }}
      ADMIN_JWT_SECRET: ${{ vars.ADMIN_JWT_SECRET }}
      API_TOKEN_SALT: ${{ vars.API_TOKEN_SALT }}
      TRANSFER_TOKEN_SALT: ${{ vars.TRANSFER_TOKEN_SALT }}

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Step 3: Create .env file
      - name: Create .env file
        run: |
          echo "DATABASE_CLIENT=$DATABASE_CLIENT" >> .env
          echo "DATABASE_HOST=$DATABASE_HOST" >> .env
          echo "DATABASE_PORT=$DATABASE_PORT" >> .env
          echo "DATABASE_NAME=$DATABASE_NAME" >> .env
          echo "DATABASE_USERNAME=$DATABASE_USERNAME" >> .env
          echo "DATABASE_PASSWORD=$DATABASE_PASSWORD" >> .env
          echo "APP_KEYS=$APP_KEYS" >> .env
          echo "ADMIN_JWT_SECRET=$ADMIN_JWT_SECRET" >> .env
          echo "API_TOKEN_SALT=$API_TOKEN_SALT" >> .env
          echo "TRANSFER_TOKEN_SALT=$TRANSFER_TOKEN_SALT" >> .env
          echo "POSTGRES_USER=$DATABASE_USERNAME" >> .env
          echo "POSTGRES_PASSWORD=$DATABASE_PASSWORD" >> .env
          echo "POSTGRES_DB=$DATABASE_NAME" >> .env

      # Step 5: Copy files to DigitalOcean using SCP with Password
      
      - name: Copy files to DigitalOcean
        run: |
          sshpass -p "$DO_PASSWORD" scp -o StrictHostKeyChecking=no -r . $DO_USERNAME@$DO_HOST:~/software-finder
          sshpass -p "$DO_PASSWORD" scp -o StrictHostKeyChecking=no .env $DO_USERNAME@$DO_HOST:~/software-finder/.env

      # Step 6: Deploy to DigitalOcean via SSH
      - name: Deploy to DigitalOcean via SSH
        run: |
          # Use sshpass for password-based SSH authentication
          sshpass -p "$DO_PASSWORD" ssh -o StrictHostKeyChecking=no $DO_USERNAME@$DO_HOST << 'EOF'
            cd software-finder || exit 1
            docker-compose down
            docker-compose up -d
          EOF
